### ISSUE TITLE
Suggestion: The default fmt string should include the name of the function rather than "LOG DERIVE"

### ISSUE THREAD

**Issue by TedDriggs** [elichai/log-derive#10]
The current default format string is good advertising for the crate, but more or less requires that I change it, and then I'm repeating the name of the function twice, once for the `fn` declaration, and once in the format string. Having the default format string be the function name instead would make it more useful by default in my opinion.

**Comment by elichai** [comment]
Yes. 
That wasn't to advertise the crate, It was to help me distinguish the logs that came from the macro from other logs, but now that I published it I need to change it.
I'll do something like `fn foo() => {:?}`

**Comment by elichai** [comment]
Done. https://github.com/elichai/log-derive/commit/3728d2ea5a1fff880d92e74491758872c7f54717
