### ISSUE TITLE
Using logfn for tests

### ISSUE THREAD

**Issue by pickfire** [elichai/log-derive#16]
Any examples to use `logfn` for tests?

Maybe instead of using `log` use `dbg!` would seems very useful when debugging, no need to initialize logger, could be used for quick development.

**Comment by elichai** [comment]
in tests I have a function that initializes a logger. and I initialize it at the start of the test.
I think this is a question more for https://github.com/rust-lang-nursery/log then for this crate specifically

**Comment by pickfire** [comment]
@elichai Thanks a lot for the quick answer, I guess this question is not really helpful in this crate, maybe i will see different use case.
