### ISSUE TITLE
Generated code shouldn't assume Ok and Err are available

### ISSUE THREAD

**Issue by TedDriggs** [elichai/log-derive#4]
@dtolnay has previously pointed out the perils of assuming certain types are available when generating Rust code. `serde` and `syn` have their own hidden re-exports which they reference when needing types or variants from the std library.

At the moment, the generated code makes bare reference to `Ok` and `Err` if it thinks it's found a result. This should probably point to a hidden export from this crate instead. That will require moving the macro itself to a new crate that `log-derive` re-exports the macro from, as proc macro crates still can't export anything but proc macros.

Also, sadly using `std::result::Result::Ok` won't work either, as then the library no longer functions on `no_std`.

**Comment by TedDriggs** [comment]
I think you could sidestep this by using the `map` and `map_err` methods to avoid ever referencing the variant. Something like:

```rust
quote! {
    fn temp() {
        (#closure)()
            .map(|result| { #ok_expr; result })
            .map_err(|err| { #err_expr; err })
    }
}
```

**Comment by elichai** [comment]
Hmm maybe I'll use `core::result::Result::Ok`?
the core/std will be a problem even if I used re exports.

**Comment by TedDriggs** [comment]
I think the `map` trick is your best bet

**Comment by elichai** [comment]
A quick test shows it's the exact same ASM code so I'll do that, Thanks!
https://godbolt.org/z/PDq2Bq
